import { Cliente } from './cliente.model';
import { PedidoDetalle } from './pedido-detalle.model';
import { Cobranza } from './cobranza.model';
import { Vendedor } from './vendedor.model';
import { Orden } from './orden.model';
import { ListaPrecio } from './lista-precio.model';
import { Canal } from './canal.model';
export interface Pedido {
  codPedido: number;
  anulado: boolean;
  codEmpresaErp: string;
  codSucursalErp: string;
  codVendedorErp: string;
  listaPrecio: ListaPrecio;
  codEmpresa: number;
  codSucursal: number;
  estado: string;
  modoEntrega: string;
  observacion: string;
  fechaAnulacion: Date;
  fechaCreacion: Date;
  fechaPedido: string;
  fechaPedidoReal: string;
  fechaModificacion: string;
  porcDescuento: number;
  importeDescuento: number;
  importeIva5: number;
  importeIva10: number;
  importeIvaExenta: number;
  importeNeto: number;
  importeTotal: number;
  descuentoProducto: number;
  subTotal: number;
  totalKg: number;
  nroPedido: number;
  codUsuarioAnulacion: number;
  codUsuarioCreacion: number;
  cliente: Cliente;
  canal: Canal;
  detalle: PedidoDetalle[];
  cobranza: Cobranza;
  vendedor: Vendedor;
  tipoPedido: string;
  cupon: string;
  contrasena?: string;
  orden?: Orden;
  codReparto?: number;
  codOrdenAbi?: number;
  codPuntoRetiro?: number;
  fechaRetiro?: string;
}
